### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [virtuald/curvesapi#1]
Hi
The following source files are without license headers:
./src/com/graphbuilder/geom/PointFactory.java
./src/com/graphbuilder/geom/Point3d.java
./src/com/graphbuilder/geom/Geom.java
./src/com/graphbuilder/geom/Point2d.java
./src/com/graphbuilder/math/ValNode.java
./src/com/graphbuilder/math/TermNode.java
./src/com/graphbuilder/math/OpNode.java
./src/com/graphbuilder/math/PascalsTriangle.java
./src/com/graphbuilder/math/func/PiFunction.java
./src/com/graphbuilder/math/func/FactFunction.java
./src/com/graphbuilder/math/func/SignFunction.java
./src/com/graphbuilder/math/func/CosFunction.java
./src/com/graphbuilder/math/func/LgFunction.java
./src/com/graphbuilder/math/func/CeilFunction.java
./src/com/graphbuilder/math/func/PowFunction.java
./src/com/graphbuilder/math/func/LnFunction.java
./src/com/graphbuilder/math/func/ModFunction.java
./src/com/graphbuilder/math/func/AcosFunction.java
./src/com/graphbuilder/math/func/MinFunction.java
./src/com/graphbuilder/math/func/RandFunction.java
./src/com/graphbuilder/math/func/AsinFunction.java
./src/com/graphbuilder/math/func/AcoshFunction.java
./src/com/graphbuilder/math/func/CoshFunction.java
./src/com/graphbuilder/math/func/Function.java
./src/com/graphbuilder/math/func/SinFunction.java
./src/com/graphbuilder/math/func/MaxFunction.java
./src/com/graphbuilder/math/func/FloorFunction.java
./src/com/graphbuilder/math/func/TanhFunction.java
./src/com/graphbuilder/math/func/LogFunction.java
./src/com/graphbuilder/math/func/TanFunction.java
./src/com/graphbuilder/math/func/AtanFunction.java
./src/com/graphbuilder/math/func/AvgFunction.java
./src/com/graphbuilder/math/func/SqrtFunction.java
./src/com/graphbuilder/math/func/SinhFunction.java
./src/com/graphbuilder/math/func/AsinhFunction.java
./src/com/graphbuilder/math/func/RoundFunction.java
./src/com/graphbuilder/math/func/EFunction.java
./src/com/graphbuilder/math/func/AbsFunction.java
./src/com/graphbuilder/math/func/CombinFunction.java
./src/com/graphbuilder/math/func/SumFunction.java
./src/com/graphbuilder/math/func/AtanhFunction.java
./src/com/graphbuilder/math/func/ExpFunction.java
./src/com/graphbuilder/math/FuncMap.java
./src/com/graphbuilder/math/AddNode.java
./src/com/graphbuilder/math/MultNode.java
./src/com/graphbuilder/math/SubNode.java
./src/com/graphbuilder/math/VarMap.java
./src/com/graphbuilder/math/VarNode.java
./src/com/graphbuilder/math/Expression.java
./src/com/graphbuilder/math/ExpressionTree.java
./src/com/graphbuilder/math/ExpressionParseException.java
./src/com/graphbuilder/math/FuncNode.java
./src/com/graphbuilder/math/PowNode.java
./src/com/graphbuilder/math/DivNode.java
./src/com/graphbuilder/curve/Polyline.java
./src/com/graphbuilder/curve/GroupIterator.java
./src/com/graphbuilder/curve/ValueVector.java
./src/com/graphbuilder/curve/Point.java
./src/com/graphbuilder/curve/ControlStringParseException.java
./src/com/graphbuilder/curve/BSpline.java: _No copyright_ GENERATED FILE
./src/com/graphbuilder/curve/MultiPath.java
./src/com/graphbuilder/curve/BezierCurve.java
./src/com/graphbuilder/curve/CubicBSpline.java
./src/com/graphbuilder/curve/ValueVectorListener.java
./src/com/graphbuilder/curve/ShapeMultiPathIterator.java
./src/com/graphbuilder/curve/LagrangeCurve.java: _No copyright_ GENERATED FILE
./src/com/graphbuilder/curve/ControlPath.java
./src/com/graphbuilder/curve/CatmullRomSpline.java
./src/com/graphbuilder/curve/BinaryCurveApproximationAlgorithm.java
./src/com/graphbuilder/curve/NaturalCubicSpline.java
./src/com/graphbuilder/curve/ParametricCurve.java
./src/com/graphbuilder/curve/NURBSpline.java
./src/com/graphbuilder/curve/ShapeMultiPath.java
./src/com/graphbuilder/curve/CardinalSpline.java
./src/com/graphbuilder/curve/Curve.java
./src/com/graphbuilder/struc/LinkedList.java
./src/com/graphbuilder/struc/Stack.java
./src/com/graphbuilder/struc/Bag.java
./demo/PointFactory.java
./demo/EditCurvePanel.java
./demo/UnsortedValueVectorPanel.java
./demo/ControlPathPanel.java
./demo/CurveDemo.java
./demo/CurveListCellRenderer.java

Please, confirm the licensing of code and/or content/s, and add license headers.

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by virtuald** [comment]
The original project source that this is a fork of did not include any licensing information in the source files. IIRC, the only file that was included was license.txt, which indicates a BSD license.

Feel free to make a pull request to add an appropriate header to the source files if that's something you care about, and I'll push a new jar.

**Comment by virtuald** [comment]
Also note that the [upstream sourceforge project](https://sourceforge.net/projects/curves/) indicates BSD license as well.

**Comment by puntogil** [comment]
https://sourceforge.net/p/curves/discussion/457804/thread/7cb3e706/?limit=25#86eb

**Comment by puntogil** [comment]
hi
can i close this bug?
