### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by ebourg** [virtuald/curvesapi#5]
Hi,

The git repository is missing the release tags, could you please add them? Here are the command to execute:

    git tag 1.05 f33f019
    git tag 1.04 25f63a4
    git tag 1.03 1946c09
    git tag 1.02 0a4c2da
    git tag 1.01 4d63b56
    git tag 1.0  e53c6c5
    git push --tags

Thank you

**Comment by virtuald** [comment]
Done, thanks!
